name: ci

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - src/**

jobs:
  dockerloginbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: |
          name="$(echo "ghcr.io/${{github.repository_owner}}/northstar-dedicated-rcon" | tr "[:upper:]" "[:lower:]")"
          cd src
          docker build --no-cache -t $name .
      - name: push image to GitHub Container Registry
        run: |
          name="$(echo "ghcr.io/${{github.repository_owner}}/northstar-dedicated-rcon" | tr "[:upper:]" "[:lower:]")"
          docker push $name:latest
